export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED'
export const GET_PROFILE_START = 'GET_PROFILE_START'

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED'
export const GET_PRODUCTS_START = 'GET_PRODUCTS_START'

export const TOGGLE_LIKE = 'TOGGLE_LIKE'
